:PROPERTIES:
:ID:       BBEFCB03-A817-4680-84D7-824357E77468
:END:
#+title: Life is a vast collection of tiny decisions made every moment
#+filetags: :permanent-note:

Every moment we make a decision to do one thing versus several others. At this very moment, I’m choosing to write. But I could have instead chosen to watch TV, play a game, read a book, play guitar, check email, browse the web, listen to music, listen to a podcast, eat something, drink something, learn something, and millions more. But I’m choosing to write. I’ll continue to write for some time, at least until I’m done with this stream of thought that I want to get on the paper (or a text file). These can be broken down into even more granular chunks where hitting each keystroke would be a tiny decision. Moving every muscle is a tiny decision. My brain chooses to do this because it thinks it’s the best thing it can do at this moment. This doesn’t say anything about right or wrong, but just that [[id:3f2d9cdf-a3b7-45a5-ade8-4e1056080b0d][You always make the best decision]].

Every single moment like this can be extrapolated and life can be viewed as a vast collection of decisions made every moment.
