:PROPERTIES:
:ID:       4BE819A2-9787-4962-9DDE-BCF12DC03C77
:END:
#+title: Attaching identity to outcomes
#+filetags: :floating-note:

We often attach identity to what we produce or what we work on. For example, if a project didn't turn out to be as successful as we thought it would, we think /we/ did it poorly. Of course, that /is/ technically the truth. But [[id:9179EC1F-A8EF-4B3E-84C4-16B2B88D20C5][we are not static]]. We change every day. In fact, we change multiple times in a day. We aren't the same person when we wake up versus during the day versus when we go back to sleep. Our moods change, energy levels change and a lot of things change. The moment we attach identity to outcomes, we associate ourselves closely with it.

We get married to this idea of a static and perfect version of ourselves. We use that as an anchor. The longer we attach our entire identity to that one thing, the longer we stay shackled to an inferior version of ourselves. The best way to break that is to [[id:2EC37E0A-D411-4395-8972-0003551D735E][Accept reality as it is]], not as we want it to be.
