:PROPERTIES:
:ID:       9C86B8B7-8E3E-4391-9619-CFAE90BD4DDC
:END:
#+title: Labels anchor us down
#+filetags: :floating-note:

We give ourselves labels to either be part of a group or to stand out in/from a group. But labels anchor us down. We are so much more than one or a few labels. [[id:9179EC1F-A8EF-4B3E-84C4-16B2B88D20C5][We are not static]]. We change our minds all the time, as we should. But labels kind of anchor us and make us afraid to accept something radically different from what we currently believe.

I was calling myself a runner when I used to run a lot. Meaning, This was a few years ago when I used to run half marathons every few weeks, did a couple of full marathons and just ran a lot. That label carried on and it became part of my identity. Now I am still referred to as a runner among my friends, but I no longer run. At least not the way I used to. For a long time, I felt like I was letting myself and everyone down because I was not living up to that label. Instead, I was [[id:4BE819A2-9787-4962-9DDE-BCF12DC03C77][Attaching identity to outcomes]].

We either shouldn't use labels or we should be aware that we associate each label with a time range. And we can say we were /X/ or we believed in /Y/ during a certain period of time. We don't have to try to live up to that expectation all the time.
