:PROPERTIES:
:ID:       6B3D20B9-B9E9-44EC-9368-84B609895690
:END:
#+title: Arbitrary future state of supposed happiness
#+filetags: :floating-note:

We often think we know what makes us happy. And "happy" is kind of a loaded term because on the surface it just means one of the pure emotions which is something that makes us feel good (to put it simply). But what we mean when we say happiness is actually a mix of fulfillment, calm and an accepting state of mind where we are at peace with how things go around us.

Happiness in this sense is an abstract concept that it's usually up to the person experiencing it and it depends on their definition and what they consider to be salient. But we often don't really know exactly what makes us happy. A lot of times, we think changing current state to a future state that is more favorable to us leads to happiness. But to really understand it and realize it, we need to /actually/ [[id:2EC37E0A-D411-4395-8972-0003551D735E][Accept reality as it is]] and be at peace with it.
