:PROPERTIES:
:ID:       887D6451-5EC8-40DB-96C8-8549D3807B5C
:END:
#+title: WebSockets

* Details
WebSockets provide persistent TCP-style connection between client and server allowing for real-time bidirectional communication. WebSockets are initiated via the HTTP upgrade protocol which allows existing TCP connection to change L7 protocols. This is convenient because you can use some of the existing HTTP session information to your advantage.

*Note: Just because clients can upgrade from HTTP to WebSockets doesn't mean that the infra will support it. Every piece of infrastructure between the client and the server will need to support WebSocket connections.*

* How it works
1. Client initiates WebSocket handshake over HTTP (with a backing TCP connection)
2. Connection upgrades to WebSocket protocol, WebSocket takes over the TCP connection
3. Both client and server send binary messages to each other over the connection
4. The connection stays open until explicitly closed

* Advantages
- full duplex (read and write) communication
- lower latency than HTTP due to reduced overhead (i.e. no headers)
- efficient for frequent messages
- wide browser support

* Disadvantages
- more complex to implement
- requires special infra
- stateful connections, can make load balancing and scaling more complex
- need to handle reconnection
