#+TITLE: Thoughts on
#+DESCRIPTION: My thoughts on things

* On Delegation
[2020-08-06 Thu]

There have been instances in my life where I've delegated some of my tasks to other people (mostly family members). This would mostly be because it's something that should be done in India and I'm not accessible (since in the US). An example for this is, buying a condo in Bangalore. Being in the US, I can't possibly check which neighborhoods are good, which condos are good, where I think I'd get a good value if I buy a condo. So, when my dad said he would do the legwork and all I had to do from my end was to sign docs and send money, I was completely okay with it, because I trusted his judgment. The mistake I made was that I delegated tasks that affect me, in some way or another, without checking on the task or the person to ensure that I get what I want, or that the best decision (according to me) would be made. Due to this, what ended up happening was, my dad bought not that great of a condo in a neighborhood that is super remote for a high price. This condo will not even go up in value by any significant amount. All in all, it was a bad investment. His reasoning was that he didn't have to go to the other end of the city for either collecting rent or fixing things, so he just got a condo very close to his house. This reasoning is flawed beyond belief. If the only thing affecting a purchase of such a significant amount is travel, that task could be delegated to someone else. You'd be paying a little more than what you would spend if you did things yourself. But you can say that's the cost of delegation. Compared to the rent I would have got, the cost of delegation would have been trivial. Also, given that it would be a new construction, there wouldn't be many issues to begin with. The other issue about collecting rent could be done online. If it had to be cash, there could have been something else arranged instead. Because of such flawed reasoning that led to an inferior financial investment, I've now ended up with a not so great condo in a bad neighborhood whose value will increase only by a very small fraction.
** Where did I screw up?
   :PROPERTIES:
   :CUSTOM_ID: where-did-i-screw-up
   :END:
I didn't check on this task. I didn't check with my dad every step along the way as to what he's doing and if I'm okay with the condo, the location, the investment, etc.. My thoughts and concerns about it would have definitely swayed the decision. After all, it was my money being invested. I've seen other instances of such blind trust I have on my parents or family that once they take up one of my tasks, I just don't get involved. This has affected me
** How do I fix this?
   :PROPERTIES:
   :CUSTOM_ID: how-do-i-fix-this
   :END:
Know that if it's your task, you are responsible for it. You may end up delegating for whatever reason, but at the end of the day, if the person you delegated to screws up, that means you screwed up. Since it's your task, you have a say in how it should be done every step along the way. Failing to do this will always lead to suboptimal results which can sometimes have long term consequences - not just with monetary losses, but also emotional (sunk cost, buyer's remorse, or just plain regrets).
* In the end, nothing matters
[2020-05-13 Wed]

Realize that in the end nothing matters. People die, others will move on. Everything will eventually be forgotten. Never chase things for the reason of wanting to be remembered forever. Just be a good person while you're alive. Be happy when you're alive. Each day you're alive consider it a gift. Lot of people don't get experience it. Lot of people die unfortunately - through no fault of theirs. This is just about being alive. There are so many such things to be grateful about - having a job, having a place to live, having family and friends, being able to afford nice things. Don't throw all of that away only to sulk about how much you think you suck at work. Because the truth is, you constantly underestimate yourself. You're much better than you think. Lately you've been a little depressed, mainly due to the fact that you're not enjoying what you're doing. You feel like you're failing at it. First of all you're exaggerating this feeling. You're not as bad as you think you are. And second of all, you're taking it too personally. Your work life shouldn't affect your personal life and vice versa. In fact nothing should affect you. You should always aim to be the happy cheerful person. That being said, happiness shouldn't be a goal. You should just do things that give you joy. Never stop yourself from being happy. In this already short life, and with the constant distractions and expectations from people on a daily basis, you hardly have time for yourself. You have to make use of your time in being happy, being peaceful, and being useful.
* On being calm
[2020-06-27 Sat]

I sat alone for a while today. It was 11.30p and I just sat by the window drinking coffee for half an hour. No phone, no music, no books, no distractions. Just me, sitting. There were lot of thoughts, like so many. Happy thoughts, sad thoughts, pondering, thinking, imagining, worrying, contemplating, having existential dread. So many things happened in those 30 minutes. What is life? What's the point of being alive? Being in this rat race, competing with peers to get meaningless recognition and fake sense of achievement. Getting stressed on a daily basis only to find myself more miserable than before. What's the point of any of this?

What I realized while sitting alone is the calm of the night. The distraction free time where you are alone with your thoughts. It's magical, it's eye opening, it's also scary. It made me sad. Not in a depressing way. But, after the first few minutes, the mind calms down and reality sets in. And reality is so much darker. The questions you tend to ask yourself have answers you mostly don't want to hear.

Every day I go from screen to screen from the time I wake up to the time I go to bed. I'm constantly dissatisfied with myself about the things that I don't do. And also the things that I do, because I always feel like I didn't do a good job. Like, somehow I'm failing at everything I do, and thereby failing at life. It's a double whammy when you feel life is pointless to begin with and also you're failing at it.

I need some time alone with my thoughts every day. I can't keep jumping from screen to screen all the time. I really have to focus on what I want in life, get my priorities down to a few and go after them.
* On blogging
[2020-07-05 Sun]

Think about blogging as teaching something to someone. Like, teaching whatever you learned. A good way to learn something is by teaching it. If you're not blogging, that means you're not reading enough. If you're not reading enough, you're not learning enough. Your blog is basically a scratch pad. Nobody reads it, so you can write about anything. You always have the fear that you may come across as stupid. Lose the fear and just write stuff. If anything, you'll get better at writing, you'll get better at explaining, and you'll get better at learning.
* Self reflection
[2020-08-02 Sun]

#+BEGIN_QUOTE
Ask yourself questions. Answer those questions. Then question those answers - Derek Sivers
#+END_QUOTE

8/23/2020

People learn when they are surprised. When you tell someone something or when you write something, do it in a way that surprises them.
* Life is short
[2020-08-02 Sun]

The universe is huge in terms of both time and space. It's has been around for 13.8 billion years, and will continue to exist for billions more. We are talking monkeys on a tiny ball of dirt in one of billions of galaxies and one of billions of star systems in that galaxy. We have only evolved over the last few thousand years and come this far. The universe doesn't give a shit about what happens to Earth, our solar system or the galaxy. It just continues to exist. We have roughly 80 years to live of which we have even fewer number of years to be productive and contribute back to society. This one lifetime is less than a blink of an eye in the cosmic timescale. It is important to recognize this because in the grand scheme of things nothing matters. Your time is wasted if you have an emotional reaction to things. It is best to leave things as they are.

[2021-04-28 Wed]

"You can discard most of the junk that clutters your mind…and clear out space for yourself… by comprehending the scale of the world… by contemplating infinite time… by thinking of the speed with which things change — each part of every thing; the narrow space between our birth and death; the infinite time before; the equally unbounded time that follows."
~Marcus Aurelius


I keep thinking about this a lot. And I’ve also talked about this with few people. I’m always amazed at how little our life matters in the vastness of both space and time. In terms of time, we occupy an extremely narrow window of about 80 years (optimistically speaking) where we’re alive. Before we were born the universe has existed for almost 14 billion years. After we die, it’ll last billions or trillions of years. We exist in this narrow window of life where we are self aware and keep trying to bend the world to our will. Thinking about this for a moment would change our perspective. Because nothing matters. As long as you’re alive you’ll be self aware. And as long as you’re self aware you’d have the freedom to choose how to live. You can make it enjoyable by choosing to care about just the few things that matter to you vs caring about everything whether or not it matters.
* Time is your currency
[2020-08-02 Sun]

Spend time wisely. Consume less, produce more. Read thought provoking books. Read slow. And think, and understand and go on a rabbit hole to figure out if you really understood what you consumed. Listening to 30 Audiobooks per year at 2x doesn't do any good because you don't remember what you read. And you don't think about it hard enough. Like Naval says, read and thoroughly understand the fundamentals. Think hard about it. You can always read other non-fiction books for "entertaining your mind intellectually".
* Happiness is a choice
[2020-08-02 Sun]

No matter what happens to you or around you, you always have the choice to be happy. It's a skill that can be developed. If you have an emotional reaction to everything, you'll end up being miserable. Life is short and if you want to make the most of it, you have to be happy. And happiness comes with being at peace with yourself.
* Handling work stress
[2020-08-02 Sun]

Work is not your life. There are good days and bad days. And everybody has a good deal of both. You have to be stoic about it. You have bad days only when you have an emotional reaction to things. If you sit back and watch your thoughts, and spent a moment to disconnect yourself from whatever happened, you'll get more clarity. The more you react to what happens to you, the worse you'll feel.
* How to read books
[2020-08-02 Sun]

Don't go chasing after number of books you read per year. It's a meaningless goal. The point of reading is to understand, learn, enrich your knowledge and most importantly, make connections in your mind either about other things you read or about how it affects your life. It's okay to leave books mid way and you don't have to get back into it if you're not interested. It's okay to spend more time and reading fewer books. You need sufficient bake time for your consumed knowledge to grow and for you to have much deeper understanding of what you read. That way, reading a few pages and thinking about it for a while is much better than reading an entire book in 2 days and forgetting the whole thing in about a week.
* On converting to another religion to marry someone
[2020-08-03 Mon]

To me, religion is a make-believe that people came up with in order to provide themselves and others meaning to their existence. Life as it is appears meaningless. The idea of existence beyond our life here on Earth provides people some sense of relief that everything they do, everything they experience when they're alive is for something. It is terrifying to think about the meaninglessness of it all.

  Every religion has its own set of morals, fables, interpretations, stories of good vs evil, rules on how to live life, on how to treat others, how to behave, and so on. Every religion advocates peace, and kindness, and compassion - to love one another, and be in harmony.

  But for some reason, many religions ask for people from other religions to convert to theirs in order to get married. This doesn't make sense. If both religions teach pretty much the same thing - like loving one another, being kind, etc. Then why is the conversion needed? If the couple involved are in love and they believe in their respective gods in their respective religions, then why convert from one to another? If the priests doing this conversion are asked about anything abstract - like, how do they know what God wants when two people from different religions come together? Do they think if a separate God exists for each religion or is it just the same for all religions, but just different interpretations? If it's different gods, then first of all, how do they know? And second of all, how does it work? Do they think one is superior than the other? Most rational priests can't and don't answer this. They all say they go by the books, even though they know that those books were written by people.

  The weirdest thing is when people who oppose when two people from different religions choose not to convert, do so with such high level of confidence that they know for a fact how these things work. It's funny when they are asked at a different time about other religions and their gods, they would answer in the most diplomatic way as of they're very liberal when it comes to different religions mingling with each other. They believe in "coexist".

  I think the biggest problem is, the people who believe and enforce these things never questioned why they do what they do. And continue doing those things for decades. Later when they try to question themselves about these things, it makes them so uncomfortable that they'll be in denial even about the possibility of them being wrong or the possibility of God not existing and everything being pointless.
* Relentless self-development
[2020-01-30 Thu]

There are times when we get laser focused on things that we want to do, but unable to do. At least for me, I tend to assess myself on being able to or unable to accomplish those things. For example, setting up my blog was a good personal project for me and I want to work on it every day and finish it. But I haven't been getting the time. Since I'm making such little progress, I feel like I'm failing at things.

Relentless self-development to me is to make sure that I'm developing myself and grow as a person in every activity I do. My metric for success is not just setting up my blog. It goes beyond that. I have to excel at many things. For example,

- I have to train my mind to do so many things - like being calm, not getting distracted often, having a positive outlook, not taking things personally, not letting things affect me, etc.
- I have to train my body - working out, running, etc.
- I have to read books, read blog posts that I've saved.
- I have to improve my technical skills.
- I have to learn new things so I can solve some of the design problems at work.
- Sometimes I have to not do anything and let my mind wander. I've noticed so many times that when I let my mind wander, it feels good. Like, all day every day my mind is always occupied with tasks. Letting it wander every now and then is very helpful.
- And sometimes I just have to chill. I can't always be putting my mind to work.

Making progress on any of these will help me grow. As long as my day to day activities are aligned with the points like above, I shouldn't feel like I'm failing at anything.

For example, if during all the free time I had this week, I either read books or blog posts. It's okay, it's good. There's still progress. And weekly reviews are there just for that. In the weekly review I can see that I'm doing good in few aspects and not good in others. I can calibrate myself accordingly.
* Procrastination
[2020-08-05 Wed]

The thing about procrastination is, it's a starting problem. Once you start the task, you'll just finish it. It always happens to the smallest of tasks. Like, sending one email, making one phone call, clicking few buttons and scheduling an appointment. That's all it takes. But I procrastinate so much that I just dread the task altogether. The task can be split into two parts - starting the task and finishing the task. Looks like I have a problem with the former, not the latter. And, I just have to fix the former. If I just focus on doing that, I'll be golden.
** What can I do about it?
   :PROPERTIES:
   :CUSTOM_ID: what-can-i-do-about-it
   :END:
There are two things I have to do:

 1. Put things on the calendar with reminders
 2. Whenever I move a task to another date, ask (or grill) myself about why I wasn't able to do it.
 3. (Bonus) Never delete a task from the to-do list. You can do so only if the task is no longer applicable (this must be extremely rare) or if you actually completed it.
*** 1. Putting things on the calendar
    :PROPERTIES:
    :CUSTOM_ID: putting-things-on-the-calendar
    :END:
    Some tasks are too trivial that it doesn't have to go on the Calendar, instead you can just do it right away. Because it takes 5 minutes or less. However, if you find yourself not doing this, you should put it on your calendar
*** 2. Moving tasks to another date
    :PROPERTIES:
    :CUSTOM_ID: moving-tasks-to-another-date
    :END:
    We are not great at planning. We either underestimate or overestimate our ability to get tasks done. This coupled with random things coming up, plus sometimes having a long workday and not having the energy to get things done, will lead to incomplete tasks. This is fine. Worst case, you'll learn more about better planning.

    Every time you move a task to another date because you couldn't get to it, ask yourself why you procrastinated in the first place. This could be due to following reasons:

 1. You forgot about it. This means, you need better reminders.
 2. You were blocked on the task by something else. This is legit and sometimes you get blocked on stuff, that's normal. The important thing to remember is, while moving the task to another date, it must be such that by the time the new date arrives, you must definitely be unblocked.
 3. You were dreading to do the task. This means, you are procrastinating for some reason. These are often the smallest of tasks. You spend more time thinking about doing it than it would take to actually do it. The action item here is to force yourself to start the task. Once you start, you can just finish it off, or at least make significant progress.

 For all the above scenarios, there is one thing in common - i.e. asking yourself if you really need to do this. Many times, I've found that I don't even have to do it. Some of my tasks are nice to have and I don't really need it. The idea is to minimize the number of tasks you do as much as possible so that you don't unnecessarily burn out doing things that don't add any value.

 So, it's good to ask yourself these 3 questions:

 - Should I really do this?
 - What happens if I don't do it?
 - Can I delegate this to someone else?
*** 3. Never delete a task from a to-do list
    :PROPERTIES:
    :CUSTOM_ID: never-delete-a-task-from-a-to-do-list
    :END:
    You add tasks to your to-do list for a reason. Sometimes you tend to procrastinate doing some of them for so long that you feel that you are able to remember it, it will be in the back of your mind and will get it at some point no matter what. So, you may delete that task. The problem with this is, you'll eventually forget until it's too late.

    For example, to get my car title changed, I had to go to the DMV. There were couple of things I needed clarity on:

 1. Is this something that the dealership would take care of?
 2. Does this need an appointment of some sort at the DMV

 Both of them could have been answered by just making couple of calls (which I didn't)

 Also, due to the pandemic I postponed going to DMV. So, that task was just sitting in my list for months, after which I just deleted that task because I thought I /had/ to get it done anyway and I /will/ at some point remember doing it. But then, it was totally lost on me that I had to do it until recently, and I added it back.

 To my surprise, when I went to the DMV for Smitha's state ID, I just asked them if they were going to change it right there. They said they would and I didn't even need an appointment. It literally took 10 minutes.
* Things I've done a 180 on (aka hard reversals)
[2020-08-09 Sun]

- My belief in a higher power
- Sleep. From thinking how I don't need it at all and can function well without it, to understanding the importance of it
- Thinking how people older than me had all the answers and had figured it all out, to realizing they're just as confused as me about other things
- From reading as many books as possible to satisfy my curiosity on subjects to reading few pages a day and relecting on it to understand it deeply

https://www.lesswrong.com/posts/e89wAuqAaChzxDoKh/what-are-your-favorite-examples-of-adults-in-and-around-this?commentId=Cjqvyrk3feGL8QDYo
* Overcorrect and undercorrect
[2020-08-09 Sun]

Many years ago I had this notion that if I assume that I'm wrong by default, then that will give me an opportunity to learn more. This led to a spiral where I was constantly assuming I was wrong and I started doubting myself. Only recently, I started working on it where I'm secure about what I know and what I don't know, and I'm willing to learn what I don't know.
* On Perfection
[2020-08-31 Mon]

You're not perfect, and you'll never be. It's impossible.  The reason is, the definition of perfection itself is subjective and keeps changing. What's perfect for you will almost never be the same for another person. Even in your mind you're the perfect person in whatever way you measure it, there will always be people better than you and there will always be someone that disagrees with that definition. Heck, even you would disagree with that definition if you ask yourself the same question a few weeks later. Perfection doesn't exist. You always make mistakes and that's how you learn. You can't chase something that doesn't exist, so you can't chase perfection.

Perfection is also a process. The whole definition of perfection must be changed to something like "just keep improving and being better than you were yesterday". That's it. No matter what you do, it'll never be enough. The only thought process in your mind should be - suck less. This doesn't always happen and there will be days where you make mistakes. There will also be days where you make blunders. But learning comes from making mistakes and blunders. If you never make mistakes, you'll never learn, so you'll never grow - which means, you'll never be "perfect" (in your definition). It's kind of paradoxical if you think about it - In order to be "perfect", you can't make mistakes. But if you don't make mistakes, you'll never learn and thus never be perfect.
* On setting hard limits for oneself
[2020-11-20 Fri]

Lately I've realized that I set rules and expectations for myself without understanding why I need that. It's just based on a random definition of "productivity" that is completely flawed.
Like, why am I supposed to read, listen to podcasts, play an instrument, learn new things, build new things, work for 8+ hours every day, exercise, meditate, do breath work every single day? First of all, I can't do all these things. So even if I do, will I really be happy?
It tends to bother me when I don't do what I consider productive things. I always thought not doing anything in a day (like, just working and watching tv and then sleeping) is bad and "mediocre". But it's okay to do that once in a while. Brains need breaks to better understand what it consumed.
What I must do is let go of the idea of having a perfect day (with a dozen things to do which can't be realistically done) and instead focus on just one or two main things and put everything else on the back burner.
Like S mentioned, coding should be my main focus. Everything else is secondary. Next, when it comes to learning new things and building new things, learning should happen when things spark my interest. So, when I come across a nice article or concept, I should dive into it. I shouldn't get frustrated for not doing it even when I don't come across something interesting. Building things should happen when I'm trying to solve a specific problem. If for example, for a couple of months I don't have any problems that I want to solve, then it should be okay not to build anything. Same with picking up guitar. It should be a leisure activity, not with the intention that I'd be a rock star someday. It's completely okay to suck.
Basically, it should all be organic. Do things that spark joy in you where you badly want to do them out of interest. Don't set limits or rules for yourself to do things.
* On communication, understanding and growing
[2020-12-23 Wed]

I recently ordered LessWrong's book set containing five books. All books contain a set of essays that were reviewed, rated and selected by the LessWrong community. The first essay titled Sketch of Communication explains the steps that /should/ be involved while updating the models one holds in their heads. This involves 3 steps:
1. Explain your model and how you arrived at it
2. Understand the other person's model and see how they arrived at it
3. Update your understanding by combining the two.

Learning happens in Step 2 where you understand where the other person is coming from and also understand how they arrived at their conclusion based on their models. One of the worst things one can do is to skip step 2. Yet, I see this happen many times with myself at work. For example, I'll have half baked understanding of something and my partial understanding of it prevents me from making progress in the task I'm doing. So, I ask a teammate as to how it works (Step 1) and they explain it (Step 2). However, since I want to be done with the task as soon as possible, I just take their conclusion as-is and go with it (skipping Step 2 completely)

This must be identified and remedied the next time I have a conversation with someone about a half-baked understanding I have about something.
* Thinking about the right way to do something vs just doing it
[2021-02-08]

A lot of times I get stuck in the analysis paralysis mode where I constantly look for the right way to solve a problem and I either spend way too much time on it or end up not doing it at all.

A recent example for this was when I was thinking about the right way to journal. Like, what would the headings be? Should I follow a template? Can I use a text expander for the template? Should I add tags for each heading in that template? Etc. I was even looking up the Journaling subreddit to look at some ideas. But then I just went ahead and freestyled it by putting in a vague enough heading that either captures the task/event/feeling. And then I added tags to capture how I'm feeling. This took a lot of stress away from me and helped me focus on Journaling instead of building a workflow.

I used to use a template to fill out things like what went well, what didn't go well, what could be better and what I learned. This started off well, but it quickly became this tedious task of filling it out every night and what ended up happening was I used to respond to those questions with just one word or just a few words. This added no value, I wasn't going back to these questions and looking at them seriously and it also added more stress.

Adding more structure to something that doesn't need a lot of structure to begin with leads to a slippery slope and it causes you to refrain from doing what you want to do.
* Tall buildings
[2021-02-23 Tue]

Tall buildings that get built mostly in downtown mostly stay that way. I don't think they ever get renovated to the extent where more floors will be built on top. At least, I've never seen that. And they are hard to tear down too. For example, how would one demolish a building when there are buildings right next to it? It maybe doable, I haven't checked. It just seems unlikely for a tall building to be torn down completely and rebuilt, unless there's a serious structural issue. That means, the heights of buildings tend to stay constant as time goes by and only smaller buildings may get rebuilt into much taller ones. Basically, it's safe to assume that the "tall enough" buildings just remain that way and a city's skyline mostly remains the same except for couple of really tall buildings that get built here and there to make a significant difference in the skyline.

[2022-08-05 Fri]
Buildings get demolished, but that's very rare. Buildings mostly stay the same.
* On viewing negative events as learning opportunities
[2021-03-03 Wed]

Negative events happen all the time. Well, that must be rephrased. Events happen all the time, we perceive it as positive or negative. Positive perception of events leads to happy thoughts and generally feeling good. Negative perception leads to stress and anxiety. An ideal way to deal with this is to suspend judgment and view each event as being completely disconnected from us. That way, no matter what happens it wouldn't affect us. However, this is extremely hard to achieve and would take years of conscious effort. In the meanwhile, what can be done is to recognize negative perceptions and treat them as learning opportunities.

For example, buying a home is a lot of stress. It's foolish to say that you are mentally prepared to handle it and you'll easily deal with it when you get stressed. This doesn't work because you don't know all the variables. There will always be surprises. Instead of over-engineering all this, it's best to react in the most natural way while also observing our thoughts and actions. Then either during the event or after, we can course correct and figure out what to do next.

In the example of home buying related stress, if this stress or how we operate is noticed while we are stressed, we can take a step back, break things down into smaller chunks, space them out and go after each of them separately. If it's noticed after the event then we can retrospect and see where we didn't do a good job and learn how to deal with it the next time.

All of this can be thought of as training. It's only when you get stressed you know exactly how to deal with it. You can't learn everything in theory and feel like you can handle it perfectly in practice.
* On not taking life too seriously
[2021-03-16]

Life is short. We make it even shorter by not living in the present. We are constantly living in the past or the future, worrying about how things should be or how it should have been. It robs us of the joy of experiencing life to the fullest. We all have just one life. I, for example, look at people who believe in superstitions and spend a lot of time and energy doing things that defy logic. They believe so deeply in superstitions that they refuse to accept the truth. They just like living in their comfort zone.

How is that different from what I feel from time to time about myself, how I get frustrated about little things like something not working, or me not being able to figure something out (yet). At the end of the day, it's time wasted for both me and those people. In both cases we're not living in the present. We're not experiencing life as beautiful as it is.

The antidote to this is, freedom. Freedom to do and feel anything. Events happen to us and they're all around us. We always have the freedom to respond to events and view them objectively. But we instead choose to get affected by them. We don't have to. It's not mandatory to sulk when things don't go our way.

Imagine a new way of looking at things. If you are engaged in an event and it's not going the way you anticipated, be extremely logical about it. The event is not blame because it just happens. It doesn't make sense to blame others (in most cases). And you can't blame yourself either. Take the example of working on a task about graphql. In an ideal world you'd finish that task quickly and get on to the next one. But for that to happen, you'd have to know a lot more about graphql. But guess what, you can create the ideal world by learning more about graphql. This is the gap that you have to fill.
* On being present
[2021-04-11 Sun]

The funny thing about humans sucking at long term thinking is, I think, mostly because of the immediate return environment our ancestors have been used to. We can’t plan so far ahead in the future and be successful in following through with it because we don’t have the long term perspective for a sustained period of time. Even though we were in immediate return environment through our evolutionary journey, we still don’t live in the present. That’s ironic.
* On handling difficulties
[2021-04-13 Tue]

#+begin_quote
Difficulties strengthen the mind, as labor does the body - Seneca
#+end_quote

We often think of difficulties as a bad thing, but they are needed more than anything to be able to grow. The way you train your muscles to become strong, so should you train your mind to become strong. Mind is intangible which is why we take mental health for granted. For us to recognize the strengths or weaknesses of our own mind it takes a bit of awareness. Once that happens it takes a lot of courage to accept that we are imperfect and make ourselves do things we generally tend to hate - sit and think and ponder about the ugliness in us. But these are necessary. If we don’t face the harsh truths we’ll continue to live in denial and keep suppressing our emotions. This will take us farther away from who we want to be. If every such negative feeling is met with the same enthusiasm as approaching a new level/challenge in a game we love to play, there’d be nothing that can stop us. Because our attitude and our perspective towards life changes.

[2021-04-30 Fri]

#+begin_quote
"If you really want to escape the things that harass you, what you’re needing is not to be in a different place but to be a different person."
~Seneca
#+end_quote


This goes back to letting go of things you cannot control. A lot of times we are in stressful situations and we just want it to end. For example, right now I want my project to end and me to come out of the situation because it’s been stressful. But this quote changes your perspective on things. What you shouldn’t wish for is for the project to end. Instead, what you should wish for is for you to change in order to better handle the stress. There’s a huge difference between running away from stress and handling it well. Both end with stress not sticking around, but I’m one you’d just not face it and get away with it, and in the other you’d learn from it and grow.

Changing your perspective and mindset helps a lot in situations like these. The important thing is to recognize, when stressful situations arise, that a lot of times you can’t a situation but you can change how you handle the situation thereby changing the situation.
* On living a happy life
[2021-04-15 Thu]

#+begin_quote
"While we wait for life, life passes" - Seneca
#+end_quote

Life is not that complicated if you have the right attitude. You can get stressed about a lot of things. You may even feel frustrated when things don’t go your way. And these can be automatic. You may not be aware that you’re feeling this way. But the thing is, everybody is as confused as you are. And everybody is trying to navigate their own life and insecurities the best way they can. People tend to get fixated on little things and forget that they don’t matter. Nothing matters since everybody is going to die one day. There is really nothing more to it. While you’re here. You just have to live the beat way you possibly can and this definition of best is totally up to you. You define your own goals (if you want to) and you hit them (if you want to). If you don’t enjoy life while you’re alive you’re really not making the best out of what you’re given.
* On focusing on the journey rather than result￼
[2021-04-17 Sat]

Was reading lesson zero on drawabox. I found a piece of text that hit home with me. As adults we focus too much on the end result. We try a bit and then we give up saying we just can't draw. This is a closed mindset. As children this never stopped us. We always drew no matter how crappy the drawing turned out. This is something that we must learn from and apply to our lives. We should approach everything with the pure joy of doing them rather than getting to the end result. The journey would be far more interesting and fulfilling that way.
* On judgment
[2021-04-22 Thu]

We tend to be judgmental of people and events, and it happens automatically that we don’t even stop and realize we’re doing it. We have to keep coming back to the realization that none of it matters and each such judgment only takes us closer to being unhappy or dissatisfied. This takes practice which can be achieved in various forms like having a sticky note on our desk, setting reminders on our phone or the best one, meditation. We have to unlearn decades of conditioning and get to a point where we don’t automatically judge anything or anyone. It takes a lot of time and effort, but it’s totally worth it.
* On fear
[2021-04-22 Thu]

Fear and anxiety are part of human nature. Fear is more in response to stimulus and was mostly applicable to our ancestors who would frequently come in contact with death (animals that want to eat them or just nature in general). What we face now in civilized society is anxiety. Anxiety doesn't depend on stimulus, but instead on anticipation about an event that could happen in the future where the outcome of that event is negative/undesirable to some degree.

Anxiety causes us constant discomfort and it's not an emotion that we like to feel. However, what we tend to forget is to take a step back and understand this anxiety. Anxiety can be understood on 2 levels. On the surface level we can try and figure out what is causing anxiety. Thinking through this for some time would give us the ability to pin point the exact event that is making us feel this way.

We must dig deeper and ask ourselves why we are feeling this way. The most common answer would be that it is threatening our values or our self identity. In other words, it is causing fear in us that makes us feel like we are losing something valuable. This goes back to the definition of fear where our existence or something we hold dear is threatened which invokes fear in us.

In modern comforts where fear doesn't really exist, anxiety about something invokes fear in us where our self identity is threatened. What we think about ourselves would not fit with what is happening to us or the way we're reacting. This makes us feel anxious.

A good example for this would be to get multiple rounds of feedback on a code review. This caused me anxiety because every new round of feedback would make me feel less skilled/smart which didn't fit well with my self conception. Basically, I thought I was smart enough to code something that received little to no feedback. But to see that I'm getting 6-8 rounds of feedback makes me feel terrible. What's important to recognize here is not the anxiety itself but what it points to. It shows me what I value and how I like to see myself. Now that this is getting challenged by events, instead of being anxious it's important to recognize (or sometimes identify) my values and course correct either my actions or my values itself.
* On death
[2021-04-25 Sun]

#+begin_quote
"What man can you show me who places any value on his time, who reckons the worth of each day, who understands that he is dying daily? For we are mistaken when we look forward to death; the major portion of death has already passed, Whatever years be behind us are in death’s hands."
~Seneca
#+end_quote

We’re always in the busyness of life that we actually forget we’re dying every single day and every single moment. The time that has passed is never coming back and we’re only getting closer and closer to death. We always think of death as this singular event that happens when we’re 80 or 90 years old. While that may be true, a different take on death which changes our perspective drastically is to think of it as a process that’s ongoing. It starts when you’re born and continues until you die. It helps to think of death as an ongoing process every day and remind ourselves that we have limited time. It is only when we truly understand how short life is and that death can come to us anytime will we start to live meaningfully.
* Writing improves thinking
[2021-07-31 Sat 10:41]
Writing improves thinking because you're forced to think slowly and put them to words and accurately framed sentences in a way that you can understand. And because you think slowly, you tend think better. Although thinking better is relative, over time you improve the way you think.

Just plain thinking is the fastest form of forming opinions. Next is saying it out loud. There's some delay between thoughts and speech. There's an even longer delay between thoughts and words on a paper (journal). And an even longer delay if you're writing a book or publishing a piece for a newspaper or something (so that you get your facts straight)
* Interest Streams
[2021-11-15 Mon]

I'm defining "interest streams" as kind of an interest rabbit-hole that takes up significant amount of time and spans across weeks. These are topics that I get interested in which makes me research about it and go deep and spend time learning about it. It could be anything at all - from learning a concept to listening to a podcast series to developing a hobby. It's something that takes time to develop and understand enough to have strong opinions about it, or even make satisfying progress to feel some kind of accomplishment.

For example, drawing is an interest stream. So is playing guitar, learning about crypto, listening to a 50-part podcast series, etc. There are only 24 hours in a day. So, we should choose how we use it. We can't afford to spend our waking hours chasing something that doesn't fulfill us. I choose interest streams mostly because I find a deep sense of satisfaction when I learn something about it.

We cannot pursue multiple interest streams, for two reasons:
1. There's really not enough time to make enough progress to hold or even form opinions on the subject.
2. The regret of not finishing something is bothersome and there are chances of feeling like a quitter. We may be genuinely interested in things, but there's only a finite amount of time and resources we can dedicate to learning it.

How do we overcome this?

One thing we /shouldn't/ do is to stop ourselves from exploring new ideas. We must and should explore them. We can set expectations from ourselves that we may lose interest over time, or something more important may come along and we'd have to drop it.

The other thing we can do is to use our time and attention as a currency. We can come up with a realistic number of interest streams we can handle - this must not be an ambitious number because there are many external factors that play into us not being able to devote enough time to it. Once we come up with this number, we can always make sure that we stick to those interests. If a new idea happens to come along that we want to pursue, we'd have to drop one of them that we're currently pursuing. If we're unable to drop one, it goes into the backburner and it must be revisited later. If, say, after a month we still want to pursue it, we can ask ourselves the same question. Depending on the answer, it'll either stay in the backburner, or get picked up to be pursued, or get deleted from the backburner.

One thing to note here is that the items in the backburner, if growing, shouldn't be a discouragement or be any indication that I'm wasting time. A growing list in the backburner actually means that I'm exploring so many new ideas and some percentage of that was so interesting to me that I wish to spend weeks or months learning about it. So, this should in fact be an encouragement to explore more ideas.
* On Karma
[2022-02-19 Sat]

People talk about karma in a way that implies that if one does a bad thing, then a bad thing will happen to them in future. This never really made sense to me. First of all, there are no checks and balances in life where everything that everybody does is tallied. Here's an example that one of my friends gave me when I asked her to explain karma - "I dumped someone when I was in college, I later got dumped by someone after a few years. That's karma".

I disagree with this strongly. People seem to associate a good deed and a bad deed in the same domain. It's always about hurting someone and getting hurt, dumping someone and getting dumped, helping someone financially and getting helped financially. Why should it stay in the same domain? What happens to the pending incoming good/bad deed when the recepient no longer exists or in any capacity to accept that good/bad deed?

This is how I think of karma. It's more collaborative and supposed to be taken as a way of leading your life. For example, if you do good to people and lead by example, people around you will be inclined to behave the same way and they will also do good to others. As this keeps happening, it is likely that someone will do a good deed for you (mostly not knowing that you started it). That's how karma comes back. Same goes with doing a bad deed. If you cheat people around you and people think you're unreliable, and if a lot of people live this way, then people's perception of other people will be that nobody is reliable and they'll act accordingly. This would also come back to you and you get affected.
* Difference between interest and obsession
[2022-02-27 Sun]

An interest is where you're keen on learning about something and you find a book and read through it. This will be more like reading any other book, except it's done with a little more concentration than usual and a little more reflection after reading. Example: learning about Systems Thinking is an interest where you work through one book, pause after you read a bit, reflect and try to apply it to your life. Same with the concept of 12-week year.

An obsession is where you spend a disproportionate amount of time consuming information on a topic from various sources - Reddit, YouTube, blogposts, etc. You tend to prioritize this obsession over actual work that you have to do. You spend time before falling asleep where you read/watch stuff about this t Example: ergo mech keyboard, emacs, etc.
* On having little control over one's own interests
11/9

I used to have specific interests as I was growing up and they have changed drastically. This is expected since we grow as people. I used to think death metal was so awesome that I'd listen to it my entire life. That didn't happen. Same thing happened for rock music. I listen to more EDM now mainly because lack of lyrics and good beats helps me focus at work. Same thing for Audiobooks, certain podcasts, book topics, things I was generally curious about (like astrophysics, calculus, etc).

We think we know ourselves well enough that we can accurately predict what we'd spend more time doing. And we do this by looking at our current interests and obsessions. The shifts in my own interests have surprised me, to say the least. This makes me raise two questions:
1. How much are we control of ourselves? We're definitely fooling ourselves in that regard.
2. How well do we know ourselves? We should be experts in ourselves but we get surprised by our own actions and shifts in interests.
* There's no good or bad, only best
We often have quick response to things which are mostly binary. Either something is good or something is bad. Once we have this kind of a binary response, we then think about how good or how bad it was. For example, was the meditation good or bad? Was the workout good or bad? I feel like that's the wrong question to ask. A better question is "did you do your best?". Because that's what matters. At any point things may turn out bad for various reasons most of which are not in our control. The only thing that's in our control is if we did our best.

For example, a 1 hour meditation session may be full of distractions and being restless. A simplistic way of thinking about this meditation session is that it was bad. But the whole point of meditation is to notice your mind and thoughts and bring it back to the present moment. If I did that sincerely, then that means I did my best. There are always good days and bad days. But every session can be the best if I did my best. So if we start doing our best, then the question of something being good or bad becomes meaningless. 

Same for workout. A workout that's cut short because I'm feeling too tired and spent to continue is not a bad workout. It's actually the best because I gave it my best to the point where I could no longer continue. 

This applies to everything that /we/ do and not things that happen to us. For example, a food we eat may be objectively bad but the question of did I do my best would become meaningless.
* How little control we have
We tend to default to this illusion that we have a lot of control over situations. But in reality, we have very little control. We always underestimate the number of factors or variables that are involved in influencing a situation. 

At some point we come to this realization that we don't have a lot of control over things or situations. And we start to believe that the only things we have control over are thoughts and actions.

Thoughts here refer to both thoughts and opinions, just for simplicity sake. I'd argue that we don't really have a lot of control over either of them. 

For example, thoughts are something that is completely outside our control. The origin of thoughts, that is. We don't know when a thought arises. We don't know if a thought is coming to the surface of our mind. We just become aware of it after it's already at the surface. A lot of these thoughts are triggered by sensory inputs - we see something that triggers a thought or a memory. We hear something which makes us start thinking about it or a related subject. We eat, we feel, we smell, all of which would likely induce thoughts. But imagine you're in a dark room and there's really no sensory inputs, you'd start thinking about what happened at work, a problem you were trying to solve, a conversation you had with someone, or an event that's coming up which you're anxious about. It could be anything. You don't /choose/ to think about it. It just comes to your mind. You don't have control over the origin of the thought. You can only control whether or not you want to engage with it. So, we basically don't have the level of control that we think we do. 

When it comes to opinions, we think that opinions are something that's well-formed, based on data and after spending enough time pondering over a subject. But there are biases that come into play that mess with it. And that is fine. We're humans after all. We have biases, we have mental shortcuts, our brains constantly try to make sense of the world anyway. 

So let's take the scenario of us changing our opinions. We'd believe in one thing and then we would look at contradictory data, we are self aware rational beings, and we decide to change our opinion on that topic. That only works for cases where we're /aware/ of that bias we have and are willing to change our opinions. What about the ones we're unaware of? The ones we're completely oblivious to? Do we have control and choose not to change?

What about opinions on having a kid? For decades, I was firm in my belief that I don't want kids. But in the last couple of years, something changed and now I want kids. What changed? People around me have kids, but that was the case several years ago as well. So, it's not that. Family and societal pressures? Sure, but that would make me feel like I /have to/ have kids. But I feel like I /want to/ have kids. One could say it's the hormones. Or going by the Selfish Gene theory, it's the gene that wants to propagate and we're all just carriers for that gene. We're just the vehicles. This means we have even less control over our thoughts and opinions. 

If this is the case, what are we even? 
